services:
  postgresql:
    build:
      context: ./Database
    environment:
      - POSTGRES_USER=apiUser
      - POSTGRES_PASSWORD=1_L0VE_D@1
      - POSTGRES_DB=countryDB
    ports:
      - 5432:5432


  api:
    build:
      context: ./HttpAPI
    expose:
      - "3141"  
    deploy:
      replicas: 2
    labels:
      - traefik.http.routers.api.rule=Host(`localhost`) && PathPrefix(`/api`)
      - traefik.http.services.api.loadbalancer.sticky.cookie=true
      - traefik.http.services.api.loadbalancer.sticky.cookie.name=RouteID
    
   
   
  webserver:
    build:
      context: ./StaticWebServer
    expose:
      - "80"  
    deploy:
      replicas: 2
    labels:
      - traefik.http.routers.webserver.rule=Host(`localhost`)
    
    

  traefik:
    image: traefik
    command:
      - --api.insecure=true
      - --providers.docker
      - --log.level=DEBUG
      - --accesslog=true
      - --log.filePath=/logs/traefik.log
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock #Docker socket
      - ./logs/:/logs/
      #TODO : certificate TLS
    ports:
      - "80:80"
      - "3141:3141"
      - "8080:8080"