services:
  postgresql:
    build:
      context: ./Database
    environment:
      - POSTGRES_USER=apiUser
      - POSTGRES_PASSWORD=1_L0VE_D@1
      - POSTGRES_DB=countryDB
    ports:
      - 5432:5432

  api:
    build:
      context: ./HttpAPI
    expose:
      - "3141"  
    deploy:
      replicas: 1
    labels:
      - traefik.http.routers.api.rule=Host(`localhost`) && PathPrefix(`/api/`)


  webserver:
    build:
      context: ./StaticWebServer
    expose:
      - "80"  
    deploy:
      replicas: 1
    labels:
      - traefik.http.routers.webserver.rule=Host(`localhost`)



  traefik:
    image: traefik
    command:
      - --api.insecure=true
      - --providers.docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "80:80"
      - "3141:3141"
      - "8080:8080"